server:
  port: 8081 #项目端口

dubbo:
  application:
    name: bussiness
  protocol:
    name: dubbo
  registry:
    address: zookeeper://139.196.176.148:2181




spring:
  datasource:
    name: seata
    url: jdbc:mysql://127.0.0.1:3306/seata?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
